---
language: python
python: "3.6"
sudo: required
before_install:

install:
  - pip install ansible

script:
  - ansible-playbook -i inventory/travis test.yml --syntax-check
  - ansible-playbook -i inventory/travis test.yml
