- name: Ensure rabbit uses "localhost" as hostname
  register: rabbitmq_hostname_stat
  notify: rabbitmq restart
  lineinfile:
    path: /etc/rabbitmq/rabbitmq-env.conf
    line: 'NODENAME=rabbit@localhost'
    create: yes
    mode: "0644"

- name: restart rabbit if is necessary
  when: rabbitmq_hostname_stat is changed
  service:
    name: rabbitmq-server
    state: restarted

- name: Generate main config file
  notify: rabbitmq restart
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    mode: "0664"

- name: Generate folder for extra config files
  file:
    path: /etc/rabbitmq/rabbitmq.conf.d
    state: directory
    mode: "0775"

- name: copy extra config files
  when: rabbitmq_extra_files
  with_list: "{{ rabbitmq_extra_files }}"
  notify: rabbitmq restart
  copy:
    src: "{{ item }}"
    dest: /etc/rabbitmq/rabbitmq.conf.d
    mode: "0664"

- name: set management ui
  rabbitmq_plugin:
    names: rabbitmq_management
    state: '{{ "enabled" if rabbit_enable_management else "disabled" }}'

- name: Add rabbitmq user
  when: rabbitmq_users
  with_list: "{{ rabbitmq_users }}"
  rabbitmq_user:
    user: "{{ item.user }}"
    password: "{{ item.password }}"
    tags: "{{ item.tags }}"
    vhost: "{{ item.vhost }}"
    configure_priv: "{{ item.configure_priv }}"
    read_priv: "{{ item.read_priv }}"
    write_priv: "{{ item.write_priv }}"
    state: "{{ item.state }}"

- name: Remove guest user
  rabbitmq_user:
    user: "guest"
    state: "absent"
