- name: Ensure rabbit uses "localhost" as hostname
  notify: rabbitmq restart
  lineinfile:
    path: /etc/rabbitmq/rabbitmq-env.conf
    line: 'NODENAME=rabbit@localhost'
    create: yes
    mode: "0644"

- meta: flush_handlers

- name: Generate main config file
  notify: rabbitmq restart
  template:
    src: rabbitmq.config.j2
    dest: /etc/rabbitmq/rabbitmq.config
    mode: "0664"

- name: Generate folder for extra config files
  file:
    path: /etc/rabbitmq/rabbitmq.conf.d
    state: directory
    mode: "0775"

- name: copy extra config files
  when: rabbitmq_extra_files
  with_list: "{{ rabbitmq_extra_files }}"
  notify: rabbitmq restart
  copy:
    src: "{{ item }}"
    dest: /etc/rabbitmq/rabbitmq.conf.d
    mode: "0664"

- name: set management ui
  rabbitmq_plugin:
    names: rabbitmq_management
    state: '{{ "enabled" if rabbit_enable_management else "disabled" }}'

- name: Add rabbitmq user
  when: rabbitmq_users
  with_list: "{{ rabbitmq_users }}"
  rabbitmq_user: "{{ item }}"

- name: Remove guest user
  rabbitmq_user:
    user: "guest"
    state: "absent"
